// lib/products-data.ts
// Complete dummy product catalog for the H&M-style store

export interface Product {
  _id: string;
  name: string;
  price: number;
  originalPrice?: number;
  description: string;
  category: string;
  subcategory: string;
  images: string[];
  sizes: string[];
  colors: string[];
  rating: number;
  reviewCount: number;
  isNew: boolean;
  isSale: boolean;
  isFeatured: boolean;
  stock: number;
  sku: string;
  tags: string[];
}

// Using Unsplash for realistic fashion photos
export const PRODUCTS: Product[] = [
  // T-SHIRTS
  {
    _id: 'p001',
    name: 'Regular Fit Cotton T-shirt',
    price: 9.99,
    description: 'Regular-fit T-shirt in soft cotton jersey. Crew neck and short sleeves. A wardrobe essential that pairs effortlessly with everything.',
    category: 'men',
    subcategory: 't-shirts',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Navy'],
    rating: 4.2,
    reviewCount: 234,
    isNew: false,
    isSale: false,
    isFeatured: true,
    stock: 150,
    sku: 'TS-001',
    tags: ['basics', 'essentials', 'cotton'],
  },
  {
    _id: 'p002',
    name: 'Slim Fit Polo Shirt',
    price: 19.99,
    description: 'Slim-fit polo shirt in smooth piqué fabric. Collar, placket with buttons, and short sleeves. A timeless piece for a polished casual look.',
    category: 'men',
    subcategory: 't-shirts',
    images: [
      'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Forest Green'],
    rating: 4.5,
    reviewCount: 189,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 80,
    sku: 'TS-002',
    tags: ['polo', 'smart-casual', 'pique'],
  },
  {
    _id: 'p003',
    name: 'Graphic Print Oversized Tee',
    price: 14.99,
    originalPrice: 24.99,
    description: 'Oversized T-shirt in soft jersey with a graphic print on the chest. Dropped shoulders and a relaxed fit for an effortlessly cool look.',
    category: 'men',
    subcategory: 't-shirts',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White'],
    rating: 4.0,
    reviewCount: 87,
    isNew: false,
    isSale: true,
    isFeatured: false,
    stock: 45,
    sku: 'TS-003',
    tags: ['graphic', 'oversized', 'streetwear'],
  },
  {
    _id: 'p004',
    name: 'Linen Blend V-Neck T-shirt',
    price: 17.99,
    description: 'V-neck T-shirt in a soft linen and cotton blend. Light and breathable, perfect for warm days. Features a slightly relaxed fit.',
    category: 'men',
    subcategory: 't-shirts',
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
      'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Sand', 'White', 'Sage'],
    rating: 4.3,
    reviewCount: 156,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 90,
    sku: 'TS-004',
    tags: ['linen', 'summer', 'breathable'],
  },

  // HOODIES & SWEATSHIRTS
  {
    _id: 'p005',
    name: 'Regular Fit Hoodie',
    price: 34.99,
    description: 'Regular-fit hoodie in soft terry fabric. Features a lined drawstring hood, front pocket, and ribbed cuffs and hem. An essential piece for layering.',
    category: 'men',
    subcategory: 'hoodies',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
      'https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Black', 'Navy', 'Beige'],
    rating: 4.6,
    reviewCount: 412,
    isNew: false,
    isSale: false,
    isFeatured: true,
    stock: 200,
    sku: 'HD-001',
    tags: ['hoodie', 'essentials', 'layering'],
  },
  {
    _id: 'p006',
    name: 'Zip-Through Sweatshirt',
    price: 39.99,
    originalPrice: 49.99,
    description: 'Sweatshirt with a zip fastening and stand-up collar. Soft brushed inside for extra comfort. Side pockets with zip. Regular fit.',
    category: 'men',
    subcategory: 'hoodies',
    images: [
      'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=600&q=80',
      'https://images.unsplash.com/photo-1608228088998-57828365d486?w=600&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Dark Grey', 'Olive'],
    rating: 4.4,
    reviewCount: 203,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 60,
    sku: 'HD-002',
    tags: ['zip', 'sweatshirt', 'athleisure'],
  },
  {
    _id: 'p007',
    name: 'Relaxed Fit Crewneck Sweatshirt',
    price: 29.99,
    description: 'Relaxed-fit sweatshirt in soft cotton-blend fabric with a slightly dropped shoulder. Crew neck, ribbed collar, cuffs, and hem.',
    category: 'men',
    subcategory: 'hoodies',
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80',
      'https://images.unsplash.com/photo-1618517351616-38fb9952b5e9?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Cream', 'Brown', 'Slate Blue'],
    rating: 4.5,
    reviewCount: 178,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 110,
    sku: 'HD-003',
    tags: ['crewneck', 'relaxed', 'casual'],
  },

  // JACKETS
  {
    _id: 'p008',
    name: 'Technical Softshell Jacket',
    price: 69.99,
    description: 'Jacket in technical softshell fabric with four-way stretch and water-repellent coating. Stand-up collar, zip pockets, and regular fit.',
    category: 'men',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Forest Green'],
    rating: 4.7,
    reviewCount: 289,
    isNew: false,
    isSale: false,
    isFeatured: true,
    stock: 70,
    sku: 'JK-001',
    tags: ['jacket', 'outdoor', 'technical'],
  },
  {
    _id: 'p009',
    name: 'Slim Fit Denim Jacket',
    price: 49.99,
    originalPrice: 59.99,
    description: 'Slim-fit denim jacket in washed cotton denim. Collar, button fastening, chest pockets and side pockets. A true wardrobe classic.',
    category: 'men',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=600&q=80',
      'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Light Denim', 'Dark Denim', 'Black'],
    rating: 4.5,
    reviewCount: 321,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 55,
    sku: 'JK-002',
    tags: ['denim', 'classic', 'casual'],
  },
  {
    _id: 'p010',
    name: 'Padded Bomber Jacket',
    price: 79.99,
    description: 'Bomber jacket in woven fabric with padding for extra warmth. Ribbed collar, cuffs and hem. Front zip and side pockets. Regular fit.',
    category: 'men',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Khaki', 'Black', 'Navy'],
    rating: 4.3,
    reviewCount: 145,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 40,
    sku: 'JK-003',
    tags: ['bomber', 'padded', 'winter'],
  },
  {
    _id: 'p011',
    name: 'Trench Coat Regular Fit',
    price: 99.99,
    description: 'Classic trench coat in a woven cotton blend. Double-breasted with storm flap. Belt with buckle. Shoulder epaulettes and welt pockets.',
    category: 'men',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Camel', 'Black', 'Navy'],
    rating: 4.8,
    reviewCount: 98,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 30,
    sku: 'JK-004',
    tags: ['trench', 'coat', 'premium', 'classic'],
  },

  // JEANS
  {
    _id: 'p012',
    name: 'Slim Fit Jeans',
    price: 39.99,
    description: 'Slim-fit jeans in stretch denim for comfort and shape retention. Five-pocket design with a zip fly and button. A wardrobe essential.',
    category: 'men',
    subcategory: 'jeans',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
      'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=600&q=80',
    ],
    sizes: ['28/30', '30/30', '30/32', '32/30', '32/32', '34/32', '36/32'],
    colors: ['Mid Denim', 'Dark Denim', 'Black', 'Light Denim'],
    rating: 4.4,
    reviewCount: 567,
    isNew: false,
    isSale: false,
    isFeatured: true,
    stock: 250,
    sku: 'JN-001',
    tags: ['jeans', 'slim', 'denim', 'classic'],
  },
  {
    _id: 'p013',
    name: 'Regular Fit Straight Jeans',
    price: 44.99,
    originalPrice: 54.99,
    description: 'Regular-fit straight jeans in stretch denim. Five-pocket design with a zip fly and button. Clean finish with subtle whiskering for a natural look.',
    category: 'men',
    subcategory: 'jeans',
    images: [
      'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=600&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    sizes: ['28/30', '30/30', '30/32', '32/30', '32/32', '34/32'],
    colors: ['Light Blue', 'Dark Blue', 'Black'],
    rating: 4.3,
    reviewCount: 342,
    isNew: false,
    isSale: true,
    isFeatured: false,
    stock: 120,
    sku: 'JN-002',
    tags: ['jeans', 'straight', 'regular'],
  },
  {
    _id: 'p014',
    name: 'Loose Fit Cargo Jeans',
    price: 49.99,
    description: 'Loose-fit jeans with cargo pockets. Relaxed silhouette through the leg, mid-waist with zip fly. A trend-forward choice with practical details.',
    category: 'men',
    subcategory: 'jeans',
    images: [
      'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&q=80',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80',
    ],
    sizes: ['28/30', '30/32', '32/32', '34/32', '36/32'],
    colors: ['Light Denim', 'Dark Grey'],
    rating: 4.1,
    reviewCount: 123,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 65,
    sku: 'JN-003',
    tags: ['cargo', 'loose', 'trendy'],
  },

  // SHOES
  {
    _id: 'p015',
    name: 'Suede Chelsea Boots',
    price: 69.99,
    description: 'Chelsea boots in suede with elastic gore panels on the sides for easy slip-on wear. Stacked heel and pull tab. A sophisticated finishing touch.',
    category: 'men',
    subcategory: 'shoes',
    images: [
      'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    ],
    sizes: ['40', '41', '42', '43', '44', '45', '46'],
    colors: ['Brown', 'Black', 'Tan'],
    rating: 4.6,
    reviewCount: 178,
    isNew: false,
    isSale: false,
    isFeatured: true,
    stock: 60,
    sku: 'SH-001',
    tags: ['chelsea', 'boots', 'suede', 'premium'],
  },
  {
    _id: 'p016',
    name: 'Canvas Sneakers',
    price: 24.99,
    originalPrice: 34.99,
    description: 'Low-top sneakers in cotton canvas with rubber sole. Lace-up fastening with metal eyelets. A classic casual shoe that goes with everything.',
    category: 'men',
    subcategory: 'shoes',
    images: [
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    ],
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: ['White', 'Black', 'Navy', 'Olive'],
    rating: 4.2,
    reviewCount: 423,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 180,
    sku: 'SH-002',
    tags: ['sneakers', 'canvas', 'casual'],
  },
  {
    _id: 'p017',
    name: 'Leather Derby Shoes',
    price: 89.99,
    description: 'Derby shoes in real leather with brogue detailing. Lace-up fastening and leather-lined interior. Leather sole with rubber heel cap.',
    category: 'men',
    subcategory: 'shoes',
    images: [
      'https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=600&q=80',
      'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80',
    ],
    sizes: ['40', '41', '42', '43', '44', '45', '46'],
    colors: ['Dark Brown', 'Black'],
    rating: 4.7,
    reviewCount: 89,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 35,
    sku: 'SH-003',
    tags: ['derby', 'leather', 'formal', 'brogue'],
  },
  {
    _id: 'p018',
    name: 'Running Sneakers',
    price: 54.99,
    description: 'Running-inspired sneakers with mesh upper for breathability. Padded collar and tongue for comfort. Lightweight EVA midsole for cushioning.',
    category: 'men',
    subcategory: 'shoes',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    ],
    sizes: ['40', '41', '42', '43', '44', '45', '46'],
    colors: ['White/Blue', 'Black/Red', 'Grey/Yellow'],
    rating: 4.4,
    reviewCount: 234,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 95,
    sku: 'SH-004',
    tags: ['running', 'sport', 'sneakers'],
  },

  // WOMEN'S
  {
    _id: 'p019',
    name: 'Ribbed Jersey Dress',
    price: 29.99,
    description: 'Fitted dress in soft ribbed jersey. Round neck and short sleeves. A flattering everyday piece that can be dressed up or down.',
    category: 'women',
    subcategory: 'dresses',
    images: [
      'https://images.unsplash.com/photo-1623609163859-ca93c959b98a?w=600&q=80',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Cream', 'Dusty Rose', 'Sage'],
    rating: 4.5,
    reviewCount: 312,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 120,
    sku: 'WD-001',
    tags: ['dress', 'ribbed', 'casual', 'women'],
  },
  {
    _id: 'p020',
    name: 'Wide-Leg Linen Trousers',
    price: 34.99,
    originalPrice: 44.99,
    description: 'Wide-leg trousers in washed linen blend. High waist with elasticated waistband, side pockets, and a fluid silhouette for an effortless look.',
    category: 'women',
    subcategory: 'trousers',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4a87?w=600&q=80',
      'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Ecru', 'Black', 'Light Grey', 'Sand'],
    rating: 4.6,
    reviewCount: 189,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 85,
    sku: 'WT-001',
    tags: ['linen', 'wide-leg', 'summer', 'women'],
  },
  {
    _id: 'p021',
    name: 'Fitted Blazer',
    price: 64.99,
    description: 'Fitted single-breasted blazer. Notched lapels, front buttons, and flap front pockets. Slightly padded shoulders for a sharp silhouette.',
    category: 'women',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?w=600&q=80',
      'https://images.unsplash.com/photo-1580657018950-106cd84f44be?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Black', 'Checked'],
    rating: 4.7,
    reviewCount: 267,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 50,
    sku: 'WJ-001',
    tags: ['blazer', 'smart', 'women', 'office'],
  },
  {
    _id: 'p022',
    name: 'Satin Effect Midi Skirt',
    price: 27.99,
    originalPrice: 39.99,
    description: 'Midi skirt in satin-finish fabric. Elasticated waist and slightly flared at the hem. Smooth and elegant for both day and evening wear.',
    category: 'women',
    subcategory: 'skirts',
    images: [
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80',
      'https://images.unsplash.com/photo-1574783552568-f4e72564bdff?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Champagne', 'Black', 'Dusty Pink', 'Forest Green'],
    rating: 4.4,
    reviewCount: 143,
    isNew: false,
    isSale: true,
    isFeatured: false,
    stock: 75,
    sku: 'WS-001',
    tags: ['satin', 'midi', 'skirt', 'elegant', 'women'],
  },

  // NEW ARRIVALS
  {
    _id: 'p023',
    name: 'Oversized Knit Cardigan',
    price: 49.99,
    description: 'Oversized cardigan in soft knit fabric. V-neck, long sleeves with dropped shoulders, and a relaxed silhouette. Perfect for layering in transitional weather.',
    category: 'new-arrivals',
    subcategory: 'knitwear',
    images: [
      'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=600&q=80',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Oatmeal', 'Rust', 'Sage', 'Black'],
    rating: 4.8,
    reviewCount: 45,
    isNew: true,
    isSale: false,
    isFeatured: true,
    stock: 60,
    sku: 'NA-001',
    tags: ['cardigan', 'knitwear', 'oversized', 'new'],
  },
  {
    _id: 'p024',
    name: 'Straight Leg Chinos',
    price: 39.99,
    description: 'Straight-leg chinos in soft cotton twill. Classic five-pocket design with a zip fly. Clean and versatile for smart-casual occasions.',
    category: 'men',
    subcategory: 'trousers',
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80',
    ],
    sizes: ['28/30', '30/30', '30/32', '32/30', '32/32', '34/32', '36/32'],
    colors: ['Khaki', 'Navy', 'Olive', 'Black'],
    rating: 4.5,
    reviewCount: 198,
    isNew: true,
    isSale: false,
    isFeatured: false,
    stock: 130,
    sku: 'TR-001',
    tags: ['chinos', 'smart-casual', 'cotton'],
  },

  // SALE ITEMS
  {
    _id: 'p025',
    name: 'Puffer Jacket',
    price: 49.99,
    originalPrice: 79.99,
    description: 'Lightweight puffer jacket with down-like filling for excellent warmth. Stand-up collar, zip fastening, and packable into its own pocket.',
    category: 'sale',
    subcategory: 'jackets',
    images: [
      'https://images.unsplash.com/photo-1587491439149-bd2ff295d450?w=600&q=80',
      'https://images.unsplash.com/photo-1608228088998-57828365d486?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Red', 'Khaki'],
    rating: 4.6,
    reviewCount: 321,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 45,
    sku: 'SA-001',
    tags: ['puffer', 'winter', 'sale'],
  },
  {
    _id: 'p026',
    name: 'Fine-Knit Crew-Neck Jumper',
    price: 19.99,
    originalPrice: 34.99,
    description: 'Fine-knit crew-neck jumper in soft yarn. Ribbed collar, cuffs and hem. A versatile layering piece with a classic, timeless look.',
    category: 'sale',
    subcategory: 'knitwear',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
      'https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Camel', 'Dark Blue', 'Dark Red', 'Forest Green'],
    rating: 4.3,
    reviewCount: 267,
    isNew: false,
    isSale: true,
    isFeatured: false,
    stock: 80,
    sku: 'SA-002',
    tags: ['knit', 'jumper', 'sale', 'essentials'],
  },
  {
    _id: 'p027',
    name: 'Slim Fit Oxford Shirt',
    price: 17.99,
    originalPrice: 29.99,
    description: 'Slim-fit shirt in textured Oxford fabric. Button-down collar and chest pocket. Classic fit with long sleeves and a curved hem.',
    category: 'sale',
    subcategory: 'shirts',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue', 'Pink', 'Striped'],
    rating: 4.4,
    reviewCount: 456,
    isNew: false,
    isSale: true,
    isFeatured: true,
    stock: 95,
    sku: 'SA-003',
    tags: ['oxford', 'shirt', 'smart', 'sale'],
  },
  {
    _id: 'p028',
    name: 'Fleece Pullover',
    price: 22.99,
    originalPrice: 39.99,
    description: 'Pullover in soft anti-pill fleece. Stand-up collar with zip, kangaroo pocket, and ribbed cuffs and hem. A cosy classic for outdoor activities.',
    category: 'sale',
    subcategory: 'hoodies',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
      'https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=600&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Navy', 'Burgundy'],
    rating: 4.5,
    reviewCount: 189,
    isNew: false,
    isSale: true,
    isFeatured: false,
    stock: 70,
    sku: 'SA-004',
    tags: ['fleece', 'pullover', 'outdoor', 'sale'],
  },
];

// Helper functions
export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p._id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.isFeatured).slice(0, 8);
}

export function getNewArrivals(): Product[] {
  return PRODUCTS.filter(p => p.isNew).slice(0, 8);
}

export function getSaleProducts(): Product[] {
  return PRODUCTS.filter(p => p.isSale).slice(0, 8);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q))
  );
}
